display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Zur√ºcksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        name:
          label: Benutzername
        status:
          label: Status
          settings:
            format_custom_true: Aktiv
        roles_target_id:
          label: Rollen
        operations:
          label: Operationen
        mail:
          separator: ', '
      filters:
        status:
          group_info:
            label: Status
            group_items:
              1:
                title: Aktiv
        roles_target_id:
          expose:
            label: Rolle
        permission:
          expose:
            label: Berechtigung
  page_1:
    display_title: Seite
    display_options:
      menu:
        title: Liste
